import type { RentalBooking } from "../../../types/rental";

/** An invented rental in the shape the server sends. */
export function makeRental(over: Partial<RentalBooking> = {}): RentalBooking {
  return {
    id: "00000000-0000-4000-8000-000000000001",
    provider: "Testcar",
    operatedBy: null,
    broker: null,
    confirmationNumber: "1234567890",
    brokerReference: null,
    agreementNumber: null,
    invoiceNumber: null,
    pickupStationName: "Frankfurt Flughafen",
    pickupAddress: null,
    pickupAirportId: 1,
    pickupIata: "FRA",
    pickupLat: 50.03,
    pickupLon: 8.57,
    pickupCountry: "DE",
    pickupTimezone: "Europe/Berlin",
    returnStationName: "Frankfurt Flughafen",
    returnAddress: null,
    returnAirportId: 1,
    returnIata: "FRA",
    returnLat: 50.03,
    returnLon: 8.57,
    returnCountry: "DE",
    returnTimezone: "Europe/Berlin",
    pickupPrecision: "minute",
    returnPrecision: "minute",
    vehicleClass: "Kompakt",
    acrissCode: null,
    vehicleTraits: null,
    vehicleExample: null,
    vehicleDriven: null,
    licensePlate: null,
    odometerOutKm: null,
    odometerInKm: null,
    distanceKm: null,
    distanceSource: null,
    finalAmount: null,
    finalCurrency: null,
    finalAmountSource: null,
    lastMailSentAt: null,
    mileagePolicy: null,
    mileageCapKm: null,
    fuelPolicy: null,
    paymentTiming: null,
    price: null,
    currency: null,
    inclusions: [],
    arrivalFlightNumber: null,
    status: "scheduled",
    notes: null,
    tags: [],
    companions: [],
    userEditedFields: [],
    tripId: null,
    routeId: null,
    externalRef: null,
    oneWay: false,
    rentalDays: 4,
    cost: null,
    priceSource: null,
    invoiceFees: [],
    depositAmount: null,
    depositCurrency: null,
    depositPaidOn: null,
    depositReturnedOn: null,
    depositReturnedAmount: null,
    invoiceMissing: false,
    times: {
      pickup: {
        utc: "2026-07-01T08:00:00.000Z",
        zone: "Europe/Berlin",
        offset: "+02:00",
        local: "2026-07-01T10:00:00",
        precision: "minute",
        zoneSource: "stored",
      },
      return: {
        utc: "2026-07-05T07:30:00.000Z",
        zone: "Europe/Berlin",
        offset: "+02:00",
        local: "2026-07-05T09:30:00",
        precision: "minute",
        zoneSource: "stored",
      },
      actualPickup: null,
      actualReturn: null,
    },
    createdAt: "2026-06-01T00:00:00.000Z",
    updatedAt: "2026-06-01T00:00:00.000Z",
    ...over,
  };
}
