import type { StoryPlace } from "./stories";

export interface BulkCity {
  city: string;
  country: string;
  iso: string;
  hotel: {
    name: string;
    type: "hotel" | "hostel" | "apartment" | "guesthouse";
    stars: number | null;
    lat: number;
    lon: number;
    year: number;
    nights: number;
    price: number;
    currency: string;
    rating: number;
  };
  places: Array<{
    name: string;
    category: StoryPlace["category"];
    lat: number;
    lon: number;
    visited: boolean;
  }>;
}

/** Volume for statistics, maps and heatmaps: stays and places outside the narrated trips. */
export const BULK_CITIES: BulkCity[] = [
  {
    city: "Wien",
    country: "Austria",
    iso: "AT",
    hotel: {
      name: "Hotel Sacher",
      type: "hotel",
      stars: 5,
      lat: 48.2038,
      lon: 16.3694,
      year: 2019,
      nights: 2,
      price: 690,
      currency: "EUR",
      rating: 5,
    },
    places: [
      {
        name: "Schloss Schönbrunn",
        category: "landmark",
        lat: 48.1845,
        lon: 16.3122,
        visited: true,
      },
      { name: "Naschmarkt", category: "restaurant", lat: 48.1985, lon: 16.3638, visited: true },
      { name: "Albertina", category: "museum", lat: 48.2046, lon: 16.3681, visited: false },
    ],
  },
  {
    city: "Prag",
    country: "Czechia",
    iso: "CZ",
    hotel: {
      name: "Hotel Josef",
      type: "hotel",
      stars: 4,
      lat: 50.0901,
      lon: 14.4236,
      year: 2018,
      nights: 3,
      price: 420,
      currency: "EUR",
      rating: 4,
    },
    places: [
      { name: "Karlsbrücke", category: "landmark", lat: 50.0865, lon: 14.4114, visited: true },
      { name: "Prager Burg", category: "landmark", lat: 50.0911, lon: 14.4016, visited: true },
      { name: "Letná-Park", category: "viewpoint", lat: 50.0963, lon: 14.4202, visited: true },
    ],
  },
  {
    city: "Paris",
    country: "France",
    iso: "FR",
    hotel: {
      name: "Hôtel des Grands Boulevards",
      type: "hotel",
      stars: 4,
      lat: 48.8713,
      lon: 2.3467,
      year: 2022,
      nights: 3,
      price: 810,
      currency: "EUR",
      rating: 4.5,
    },
    places: [
      { name: "Louvre", category: "museum", lat: 48.8606, lon: 2.3376, visited: true },
      { name: "Montmartre", category: "viewpoint", lat: 48.8867, lon: 2.3431, visited: true },
      { name: "Musée d'Orsay", category: "museum", lat: 48.86, lon: 2.3266, visited: false },
    ],
  },
  {
    city: "London",
    country: "United Kingdom",
    iso: "GB",
    hotel: {
      name: "The Hoxton Southwark",
      type: "hotel",
      stars: 4,
      lat: 51.5049,
      lon: -0.1052,
      year: 2023,
      nights: 4,
      price: 980,
      currency: "GBP",
      rating: 4,
    },
    places: [
      { name: "British Museum", category: "museum", lat: 51.5194, lon: -0.127, visited: true },
      { name: "Borough Market", category: "restaurant", lat: 51.5055, lon: -0.091, visited: true },
      { name: "Sky Garden", category: "viewpoint", lat: 51.5112, lon: -0.0836, visited: true },
    ],
  },
  {
    city: "Amsterdam",
    country: "Netherlands",
    iso: "NL",
    hotel: {
      name: "Pulitzer Amsterdam",
      type: "hotel",
      stars: 5,
      lat: 52.3729,
      lon: 4.8836,
      year: 2021,
      nights: 2,
      price: 740,
      currency: "EUR",
      rating: 4.5,
    },
    places: [
      { name: "Rijksmuseum", category: "museum", lat: 52.36, lon: 4.8852, visited: true },
      { name: "Vondelpark", category: "nature", lat: 52.358, lon: 4.8686, visited: true },
      { name: "A'DAM Lookout", category: "viewpoint", lat: 52.3843, lon: 4.9018, visited: false },
    ],
  },
  {
    city: "Kopenhagen",
    country: "Denmark",
    iso: "DK",
    hotel: {
      name: "Generator Copenhagen",
      type: "hostel",
      stars: null,
      lat: 55.6842,
      lon: 12.5877,
      year: 2017,
      nights: 3,
      price: 210,
      currency: "DKK",
      rating: 3.5,
    },
    places: [
      { name: "Nyhavn", category: "landmark", lat: 55.6798, lon: 12.5908, visited: true },
      { name: "Tivoli", category: "entertainment", lat: 55.6737, lon: 12.5681, visited: true },
      { name: "Torvehallerne", category: "restaurant", lat: 55.6838, lon: 12.5702, visited: true },
    ],
  },
  {
    city: "Stockholm",
    country: "Sweden",
    iso: "SE",
    hotel: {
      name: "Hotel Skeppsholmen",
      type: "hotel",
      stars: 4,
      lat: 59.3257,
      lon: 18.0842,
      year: 2022,
      nights: 3,
      price: 5400,
      currency: "SEK",
      rating: 4,
    },
    places: [
      { name: "Vasa-Museum", category: "museum", lat: 59.328, lon: 18.0914, visited: true },
      { name: "Gamla stan", category: "landmark", lat: 59.3251, lon: 18.0711, visited: true },
      { name: "Fotografiska", category: "museum", lat: 59.3178, lon: 18.0856, visited: false },
    ],
  },
  {
    city: "Edinburgh",
    country: "United Kingdom",
    iso: "GB",
    hotel: {
      name: "Old Town Apartment",
      type: "apartment",
      stars: null,
      lat: 55.9496,
      lon: -3.1904,
      year: 2019,
      nights: 4,
      price: 640,
      currency: "GBP",
      rating: 4,
    },
    places: [
      { name: "Edinburgh Castle", category: "landmark", lat: 55.9486, lon: -3.1999, visited: true },
      { name: "Arthur's Seat", category: "viewpoint", lat: 55.9441, lon: -3.1618, visited: true },
      { name: "The Royal Mile", category: "shopping", lat: 55.9503, lon: -3.1874, visited: true },
    ],
  },
  {
    city: "Lissabon",
    country: "Portugal",
    iso: "PT",
    hotel: {
      name: "Casa do Bairro",
      type: "guesthouse",
      stars: null,
      lat: 38.7136,
      lon: -9.1445,
      year: 2018,
      nights: 3,
      price: 330,
      currency: "EUR",
      rating: 4.5,
    },
    places: [
      {
        name: "Miradouro da Senhora do Monte",
        category: "viewpoint",
        lat: 38.7193,
        lon: -9.1331,
        visited: true,
      },
      {
        name: "Time Out Market",
        category: "restaurant",
        lat: 38.7071,
        lon: -9.1459,
        visited: true,
      },
      { name: "Oceanário", category: "entertainment", lat: 38.7635, lon: -9.0937, visited: false },
    ],
  },
  {
    city: "Madrid",
    country: "Spain",
    iso: "ES",
    hotel: {
      name: "Hotel Urban",
      type: "hotel",
      stars: 5,
      lat: 40.4152,
      lon: -3.6989,
      year: 2020,
      nights: 2,
      price: 460,
      currency: "EUR",
      rating: 4,
    },
    places: [
      { name: "Museo del Prado", category: "museum", lat: 40.4138, lon: -3.6921, visited: true },
      { name: "Retiro-Park", category: "nature", lat: 40.4153, lon: -3.6845, visited: true },
      {
        name: "Mercado de San Miguel",
        category: "restaurant",
        lat: 40.4154,
        lon: -3.7089,
        visited: true,
      },
    ],
  },
  {
    city: "New York",
    country: "United States",
    iso: "US",
    hotel: {
      name: "The Standard High Line",
      type: "hotel",
      stars: 4,
      lat: 40.7408,
      lon: -74.0079,
      year: 2019,
      nights: 5,
      price: 2100,
      currency: "USD",
      rating: 4,
    },
    places: [
      { name: "Central Park", category: "nature", lat: 40.7829, lon: -73.9654, visited: true },
      { name: "High Line", category: "nature", lat: 40.748, lon: -74.0048, visited: true },
      {
        name: "Metropolitan Museum of Art",
        category: "museum",
        lat: 40.7794,
        lon: -73.9632,
        visited: true,
      },
    ],
  },
  {
    city: "San Francisco",
    country: "United States",
    iso: "US",
    hotel: {
      name: "Hotel Zephyr",
      type: "hotel",
      stars: 3,
      lat: 37.8078,
      lon: -122.4149,
      year: 2019,
      nights: 3,
      price: 890,
      currency: "USD",
      rating: 3.5,
    },
    places: [
      {
        name: "Golden Gate Bridge",
        category: "landmark",
        lat: 37.8199,
        lon: -122.4783,
        visited: true,
      },
      { name: "Alcatraz", category: "museum", lat: 37.827, lon: -122.423, visited: true },
      {
        name: "Ferry Building",
        category: "restaurant",
        lat: 37.7955,
        lon: -122.3937,
        visited: true,
      },
    ],
  },
  {
    city: "Singapur",
    country: "Singapore",
    iso: "SG",
    hotel: {
      name: "Hotel Indigo Katong",
      type: "hotel",
      stars: 4,
      lat: 1.3052,
      lon: 103.9048,
      year: 2023,
      nights: 3,
      price: 980,
      currency: "SGD",
      rating: 4.5,
    },
    places: [
      { name: "Gardens by the Bay", category: "nature", lat: 1.2816, lon: 103.8636, visited: true },
      {
        name: "Maxwell Food Centre",
        category: "restaurant",
        lat: 1.2803,
        lon: 103.8447,
        visited: true,
      },
      {
        name: "Marina Bay Sands SkyPark",
        category: "viewpoint",
        lat: 1.2834,
        lon: 103.8607,
        visited: false,
      },
    ],
  },
  {
    city: "Bangkok",
    country: "Thailand",
    iso: "TH",
    hotel: {
      name: "Riva Arun",
      type: "hotel",
      stars: 4,
      lat: 13.7437,
      lon: 100.4899,
      year: 2018,
      nights: 3,
      price: 14500,
      currency: "THB",
      rating: 4,
    },
    places: [
      { name: "Wat Arun", category: "landmark", lat: 13.7437, lon: 100.4889, visited: true },
      { name: "Wat Pho", category: "landmark", lat: 13.7465, lon: 100.4927, visited: true },
      {
        name: "Chatuchak-Wochenendmarkt",
        category: "shopping",
        lat: 13.7999,
        lon: 100.5502,
        visited: true,
      },
    ],
  },
  {
    city: "Sydney",
    country: "Australia",
    iso: "AU",
    hotel: {
      name: "QT Sydney",
      type: "hotel",
      stars: 5,
      lat: -33.8712,
      lon: 151.2073,
      year: 2020,
      nights: 4,
      price: 1650,
      currency: "AUD",
      rating: 4.5,
    },
    places: [
      {
        name: "Sydney Opera House",
        category: "landmark",
        lat: -33.8568,
        lon: 151.2153,
        visited: true,
      },
      { name: "Bondi Beach", category: "nature", lat: -33.8915, lon: 151.2767, visited: true },
      { name: "Blue Mountains", category: "nature", lat: -33.7153, lon: 150.3115, visited: false },
    ],
  },
  {
    city: "Kapstadt",
    country: "South Africa",
    iso: "ZA",
    hotel: {
      name: "Cape Heritage Hotel",
      type: "hotel",
      stars: 4,
      lat: -33.9176,
      lon: 18.4199,
      year: 2022,
      nights: 4,
      price: 12800,
      currency: "ZAR",
      rating: 4.5,
    },
    places: [
      { name: "Tafelberg", category: "viewpoint", lat: -33.9628, lon: 18.4098, visited: true },
      {
        name: "Kap der Guten Hoffnung",
        category: "nature",
        lat: -34.3568,
        lon: 18.474,
        visited: true,
      },
      { name: "Boulders Beach", category: "nature", lat: -34.1975, lon: 18.4518, visited: true },
    ],
  },
  {
    city: "Marrakesch",
    country: "Morocco",
    iso: "MA",
    hotel: {
      name: "Riad Kniza",
      type: "guesthouse",
      stars: null,
      lat: 31.6343,
      lon: -7.9941,
      year: 2017,
      nights: 3,
      price: 480,
      currency: "EUR",
      rating: 5,
    },
    places: [
      { name: "Djemaa el Fna", category: "landmark", lat: 31.6258, lon: -7.9891, visited: true },
      { name: "Jardin Majorelle", category: "nature", lat: 31.6417, lon: -8.0033, visited: true },
      { name: "Bahia-Palast", category: "museum", lat: 31.6216, lon: -7.9832, visited: true },
    ],
  },
  {
    city: "Dubai",
    country: "United Arab Emirates",
    iso: "AE",
    hotel: {
      name: "Rove Downtown",
      type: "hotel",
      stars: 3,
      lat: 25.1932,
      lon: 55.2796,
      year: 2021,
      nights: 2,
      price: 1100,
      currency: "AED",
      rating: 3.5,
    },
    places: [
      { name: "Burj Khalifa", category: "viewpoint", lat: 25.1972, lon: 55.2744, visited: true },
      { name: "Dubai Creek", category: "landmark", lat: 25.2644, lon: 55.3036, visited: true },
      {
        name: "Museum of the Future",
        category: "museum",
        lat: 25.2195,
        lon: 55.2818,
        visited: false,
      },
    ],
  },
  {
    city: "Berlin",
    country: "Germany",
    iso: "DE",
    hotel: {
      name: "Michelberger Hotel",
      type: "hotel",
      stars: 3,
      lat: 52.5069,
      lon: 13.4466,
      year: 2024,
      nights: 2,
      price: 260,
      currency: "EUR",
      rating: 4,
    },
    places: [
      {
        name: "Brandenburger Tor",
        category: "landmark",
        lat: 52.5163,
        lon: 13.3777,
        visited: true,
      },
      { name: "East Side Gallery", category: "landmark", lat: 52.505, lon: 13.4397, visited: true },
      { name: "Pergamonmuseum", category: "museum", lat: 52.5212, lon: 13.3969, visited: false },
    ],
  },
  {
    city: "Hamburg",
    country: "Germany",
    iso: "DE",
    hotel: {
      name: "25hours Hotel HafenCity",
      type: "hotel",
      stars: 4,
      lat: 53.5429,
      lon: 9.9967,
      year: 2025,
      nights: 2,
      price: 310,
      currency: "EUR",
      rating: 4.5,
    },
    places: [
      {
        name: "Elbphilharmonie",
        category: "entertainment",
        lat: 53.5413,
        lon: 9.9841,
        visited: true,
      },
      { name: "Speicherstadt", category: "landmark", lat: 53.5436, lon: 9.9937, visited: true },
      {
        name: "Miniatur Wunderland",
        category: "entertainment",
        lat: 53.5437,
        lon: 9.9885,
        visited: true,
      },
    ],
  },
];
