/**
 * Narrated demo trips: hand-written stories (not generated) that give the
 * demo account a few trips with a real arc — flights, stays, places, an
 * optional cruise or tour, and a journal. Dates are UTC ISO. German prose
 * (trip names, journal text) is intentional demo content, not code, and
 * stays as written.
 */

export interface StoryPoint {
  name: string;
  lat: number;
  lon: number;
}

export interface StoryFlight {
  airline: string;
  flightNumber: string;
  from: string;
  to: string;
  departure: string;
  arrival: string;
}

export interface StoryStay {
  name: string;
  type: "hotel" | "campsite" | "guesthouse" | "apartment" | "hostel";
  city: string;
  country: string;
  iso: string;
  lat: number;
  lon: number;
  checkIn: string;
  checkOut: string;
  board: "none" | "breakfast" | "half" | "full" | "all_inclusive";
  price: number | null;
  currency: string;
  rating: number | null;
  stars: number | null;
}

export interface StoryPlace {
  name: string;
  category:
    | "restaurant"
    | "landmark"
    | "nature"
    | "museum"
    | "entertainment"
    | "shopping"
    | "viewpoint"
    | "other";
  city: string;
  country: string;
  iso: string;
  lat: number;
  lon: number;
  visitedAt: string | null;
  rating: number | null;
  curatedId?: string;
}

export interface StoryCruise {
  ship: string;
  start: string;
  end: string;
  cabinType: "inside" | "oceanview" | "balcony" | "suite";
  price: number;
  stops: Array<{ locode: string } | { atSea: true }>;
}

export interface StoryTour {
  name: string;
  mode: "road" | "ferry" | "rail" | "foot" | "bike";
  color: string;
  stops: StoryPoint[];
}

export interface StoryJournal {
  date: string;
  title: string;
  body: string;
  mood: string;
  weather: string;
}

export interface Story {
  name: string;
  description: string;
  color: string;
  icon: string;
  status: "planned" | "in_progress" | "completed";
  category: "vacation" | "business" | "weekend" | "family" | "other";
  start: string;
  end: string;
  origin: string;
  destination: string;
  countries: string[];
  tags: string[];
  companions: string[];
  flights: StoryFlight[];
  stays: StoryStay[];
  places: StoryPlace[];
  cruise?: StoryCruise;
  tour?: StoryTour;
  journal: StoryJournal[];
}

export const STORIES: Story[] = [
  {
    name: "Island – Ringstraße",
    icon: "🌋",
    color: "#38bdf8",
    status: "completed",
    category: "vacation",
    description: "Zehn Tage einmal um die Insel: Wasserfälle, Gletscher und Mitternachtssonne.",
    start: "2024-06-08T00:00:00Z",
    end: "2024-06-17T23:59:00Z",
    origin: "München",
    destination: "Reykjavík",
    countries: ["IS"],
    tags: ["Roadtrip", "Natur"],
    companions: ["Anna"],
    flights: [
      {
        airline: "Icelandair",
        flightNumber: "FI533",
        from: "MUC",
        to: "KEF",
        departure: "2024-06-08T13:05:00Z",
        arrival: "2024-06-08T16:20:00Z",
      },
      {
        airline: "Icelandair",
        flightNumber: "FI532",
        from: "KEF",
        to: "MUC",
        departure: "2024-06-17T07:40:00Z",
        arrival: "2024-06-17T12:50:00Z",
      },
    ],
    stays: [
      {
        name: "Hotel Borg",
        type: "hotel",
        city: "Reykjavík",
        country: "Iceland",
        iso: "IS",
        lat: 64.1474,
        lon: -21.9396,
        checkIn: "2024-06-08T00:00:00Z",
        checkOut: "2024-06-10T00:00:00Z",
        board: "breakfast",
        price: 520,
        currency: "EUR",
        rating: 4.5,
        stars: 4,
      },
      {
        name: "Guesthouse Vík",
        type: "guesthouse",
        city: "Vík",
        country: "Iceland",
        iso: "IS",
        lat: 63.4186,
        lon: -19.006,
        checkIn: "2024-06-10T00:00:00Z",
        checkOut: "2024-06-12T00:00:00Z",
        board: "breakfast",
        price: 290,
        currency: "EUR",
        rating: 4,
        stars: null,
      },
      {
        name: "Hótel Höfn",
        type: "hotel",
        city: "Höfn",
        country: "Iceland",
        iso: "IS",
        lat: 64.2539,
        lon: -15.2082,
        checkIn: "2024-06-12T00:00:00Z",
        checkOut: "2024-06-13T00:00:00Z",
        board: "none",
        price: 185,
        currency: "EUR",
        rating: 3.5,
        stars: 3,
      },
      {
        name: "Camping Hlíð",
        type: "campsite",
        city: "Mývatn",
        country: "Iceland",
        iso: "IS",
        lat: 65.645,
        lon: -16.912,
        checkIn: "2024-06-13T00:00:00Z",
        checkOut: "2024-06-15T00:00:00Z",
        board: "none",
        price: null,
        currency: "EUR",
        rating: 4,
        stars: null,
      },
      {
        name: "Hotel Kea",
        type: "hotel",
        city: "Akureyri",
        country: "Iceland",
        iso: "IS",
        lat: 65.6816,
        lon: -18.0878,
        checkIn: "2024-06-15T00:00:00Z",
        checkOut: "2024-06-17T00:00:00Z",
        board: "breakfast",
        price: 410,
        currency: "EUR",
        rating: 4.5,
        stars: 4,
      },
    ],
    places: [
      {
        name: "Þingvellir",
        category: "nature",
        city: "Þingvellir",
        country: "Iceland",
        iso: "IS",
        lat: 64.2559,
        lon: -21.1299,
        visitedAt: "2024-06-09T10:00:00Z",
        rating: 5,
        curatedId: "world-heritage:1152",
      },
      {
        name: "Geysir",
        category: "nature",
        city: "Haukadalur",
        country: "Iceland",
        iso: "IS",
        lat: 64.3104,
        lon: -20.3024,
        visitedAt: "2024-06-09T13:00:00Z",
        rating: 4,
      },
      {
        name: "Gullfoss",
        category: "nature",
        city: "Bláskógabyggð",
        country: "Iceland",
        iso: "IS",
        lat: 64.3271,
        lon: -20.1199,
        visitedAt: "2024-06-09T15:00:00Z",
        rating: 5,
      },
      {
        name: "Seljalandsfoss",
        category: "nature",
        city: "Rangárþing eystra",
        country: "Iceland",
        iso: "IS",
        lat: 63.6156,
        lon: -19.9886,
        visitedAt: "2024-06-10T11:00:00Z",
        rating: 5,
      },
      {
        name: "Reynisfjara",
        category: "nature",
        city: "Vík",
        country: "Iceland",
        iso: "IS",
        lat: 63.4044,
        lon: -19.045,
        visitedAt: "2024-06-11T09:00:00Z",
        rating: 4,
      },
      {
        name: "Jökulsárlón",
        category: "viewpoint",
        city: "Vatnajökull",
        country: "Iceland",
        iso: "IS",
        lat: 64.0484,
        lon: -16.1794,
        visitedAt: "2024-06-12T14:00:00Z",
        rating: 5,
        curatedId: "world-heritage:1604",
      },
      {
        name: "Dettifoss",
        category: "nature",
        city: "Norðurþing",
        country: "Iceland",
        iso: "IS",
        lat: 65.8147,
        lon: -16.3846,
        visitedAt: "2024-06-14T12:00:00Z",
        rating: 4,
      },
      {
        name: "Goðafoss",
        category: "nature",
        city: "Þingeyjarsveit",
        country: "Iceland",
        iso: "IS",
        lat: 65.6828,
        lon: -17.5502,
        visitedAt: "2024-06-15T10:00:00Z",
        rating: 4,
      },
    ],
    tour: {
      name: "Ringstraße",
      mode: "road",
      color: "#38bdf8",
      stops: [
        { name: "Reykjavík", lat: 64.1466, lon: -21.9426 },
        { name: "Þingvellir", lat: 64.2559, lon: -21.1299 },
        { name: "Geysir", lat: 64.3104, lon: -20.3024 },
        { name: "Gullfoss", lat: 64.3271, lon: -20.1199 },
        { name: "Seljalandsfoss", lat: 63.6156, lon: -19.9886 },
        { name: "Vík", lat: 63.4186, lon: -19.006 },
        { name: "Jökulsárlón", lat: 64.0484, lon: -16.1794 },
        { name: "Höfn", lat: 64.2539, lon: -15.2082 },
        { name: "Mývatn", lat: 65.6039, lon: -16.9961 },
        { name: "Akureyri", lat: 65.6885, lon: -18.1262 },
      ],
    },
    journal: [
      {
        date: "2024-06-09T20:00:00Z",
        title: "Goldener Kreis",
        body: "Þingvellir am Morgen fast menschenleer, der Geysir brav alle paar Minuten.",
        mood: "begeistert",
        weather: "bewölkt, 11 °C",
      },
      {
        date: "2024-06-11T21:00:00Z",
        title: "Schwarzer Strand",
        body: "Reynisfjara bei Wind — die Wellen kommen weiter, als man denkt.",
        mood: "ehrfürchtig",
        weather: "Sturm, 9 °C",
      },
      {
        date: "2024-06-12T22:00:00Z",
        title: "Eisberge",
        body: "Jökulsárlón bei Mitternachtssonne. Robben zwischen den Schollen.",
        mood: "glücklich",
        weather: "sonnig, 12 °C",
      },
      {
        date: "2024-06-14T20:00:00Z",
        title: "Mývatn",
        body: "Mücken, Lava und das Naturbad am Abend.",
        mood: "entspannt",
        weather: "sonnig, 15 °C",
      },
    ],
  },
  {
    name: "Japan – Tokio bis Kyoto",
    icon: "🗾",
    color: "#f472b6",
    status: "completed",
    category: "vacation",
    description: "Kirschblüte in Tokio, Tempel in Kyoto und Nara, Burg Himeji.",
    start: "2025-04-01T00:00:00Z",
    end: "2025-04-12T23:59:00Z",
    origin: "Frankfurt",
    destination: "Osaka",
    countries: ["JP"],
    tags: ["Kirschblüte", "Bahn"],
    companions: ["Anna", "Jonas"],
    flights: [
      {
        airline: "Lufthansa",
        flightNumber: "LH716",
        from: "FRA",
        to: "HND",
        departure: "2025-04-01T11:50:00Z",
        arrival: "2025-04-02T00:05:00Z",
      },
      {
        airline: "Lufthansa",
        flightNumber: "LH741",
        from: "KIX",
        to: "FRA",
        departure: "2025-04-12T01:25:00Z",
        arrival: "2025-04-12T15:10:00Z",
      },
    ],
    stays: [
      {
        name: "Hotel Gracery Shinjuku",
        type: "hotel",
        city: "Tokio",
        country: "Japan",
        iso: "JP",
        lat: 35.6948,
        lon: 139.702,
        checkIn: "2025-04-02T00:00:00Z",
        checkOut: "2025-04-06T00:00:00Z",
        board: "none",
        price: 118000,
        currency: "JPY",
        rating: 4,
        stars: 3,
      },
      {
        name: "Hotel Granvia Kyoto",
        type: "hotel",
        city: "Kyoto",
        country: "Japan",
        iso: "JP",
        lat: 34.9855,
        lon: 135.7588,
        checkIn: "2025-04-06T00:00:00Z",
        checkOut: "2025-04-10T00:00:00Z",
        board: "breakfast",
        price: 164000,
        currency: "JPY",
        rating: 4.5,
        stars: 4,
      },
      {
        name: "Cross Hotel Osaka",
        type: "hotel",
        city: "Osaka",
        country: "Japan",
        iso: "JP",
        lat: 34.6693,
        lon: 135.5013,
        checkIn: "2025-04-10T00:00:00Z",
        checkOut: "2025-04-12T00:00:00Z",
        board: "none",
        price: 52000,
        currency: "JPY",
        rating: 4,
        stars: 4,
      },
    ],
    places: [
      {
        name: "Sensō-ji",
        category: "landmark",
        city: "Tokio",
        country: "Japan",
        iso: "JP",
        lat: 35.7148,
        lon: 139.7967,
        visitedAt: "2025-04-03T09:00:00Z",
        rating: 5,
      },
      {
        name: "Shibuya Crossing",
        category: "landmark",
        city: "Tokio",
        country: "Japan",
        iso: "JP",
        lat: 35.6595,
        lon: 139.7005,
        visitedAt: "2025-04-03T19:00:00Z",
        rating: 4,
      },
      {
        name: "Tokyo Skytree",
        category: "viewpoint",
        city: "Tokio",
        country: "Japan",
        iso: "JP",
        lat: 35.7101,
        lon: 139.8107,
        visitedAt: "2025-04-04T17:00:00Z",
        rating: 4,
      },
      {
        name: "Kinkaku-ji",
        category: "landmark",
        city: "Kyoto",
        country: "Japan",
        iso: "JP",
        lat: 35.0394,
        lon: 135.7292,
        visitedAt: "2025-04-07T10:00:00Z",
        rating: 5,
        curatedId: "world-heritage:688",
      },
      {
        name: "Fushimi Inari-taisha",
        category: "landmark",
        city: "Kyoto",
        country: "Japan",
        iso: "JP",
        lat: 34.9671,
        lon: 135.7727,
        visitedAt: "2025-04-08T07:00:00Z",
        rating: 5,
      },
      {
        name: "Bambuswald Arashiyama",
        category: "nature",
        city: "Kyoto",
        country: "Japan",
        iso: "JP",
        lat: 35.017,
        lon: 135.6713,
        visitedAt: "2025-04-08T15:00:00Z",
        rating: 4,
      },
      {
        name: "Tōdai-ji",
        category: "landmark",
        city: "Nara",
        country: "Japan",
        iso: "JP",
        lat: 34.689,
        lon: 135.8398,
        visitedAt: "2025-04-09T11:00:00Z",
        rating: 5,
        curatedId: "world-heritage:870",
      },
      {
        name: "Burg Himeji",
        category: "landmark",
        city: "Himeji",
        country: "Japan",
        iso: "JP",
        lat: 34.8394,
        lon: 134.6939,
        visitedAt: "2025-04-10T10:00:00Z",
        rating: 5,
        curatedId: "world-heritage:661",
      },
      {
        name: "Dōtonbori",
        category: "restaurant",
        city: "Osaka",
        country: "Japan",
        iso: "JP",
        lat: 34.6687,
        lon: 135.5019,
        visitedAt: "2025-04-11T19:00:00Z",
        rating: 4,
      },
    ],
    tour: {
      name: "Mit dem Shinkansen",
      mode: "rail",
      color: "#f472b6",
      stops: [
        { name: "Tokio", lat: 35.6812, lon: 139.7671 },
        { name: "Kyoto", lat: 34.9858, lon: 135.7588 },
        { name: "Nara", lat: 34.6851, lon: 135.8048 },
        { name: "Himeji", lat: 34.8269, lon: 134.6906 },
        { name: "Osaka", lat: 34.7025, lon: 135.4959 },
      ],
    },
    journal: [
      {
        date: "2025-04-03T22:00:00Z",
        title: "Hanami",
        body: "Picknick unter Kirschblüten im Ueno-Park, halb Tokio war da.",
        mood: "glücklich",
        weather: "sonnig, 18 °C",
      },
      {
        date: "2025-04-08T21:00:00Z",
        title: "Tausend Tore",
        body: "Um sieben Uhr früh am Fushimi Inari — ab neun ist es voll.",
        mood: "ruhig",
        weather: "diesig, 15 °C",
      },
      {
        date: "2025-04-10T21:00:00Z",
        title: "Die weiße Burg",
        body: "Himeji von innen: steile Treppen, großartige Aussicht.",
        mood: "begeistert",
        weather: "sonnig, 19 °C",
      },
    ],
  },
  {
    name: "Toskana",
    icon: "🍷",
    color: "#fb923c",
    status: "completed",
    category: "vacation",
    description: "Florenz, Weinberge rund um San Gimignano und die Hügel des Val d'Orcia.",
    start: "2023-09-09T00:00:00Z",
    end: "2023-09-17T23:59:00Z",
    origin: "München",
    destination: "Pisa",
    countries: ["IT"],
    tags: ["Genuss", "Roadtrip"],
    companions: ["Anna"],
    flights: [
      {
        airline: "Air Dolomiti",
        flightNumber: "EN8190",
        from: "MUC",
        to: "FLR",
        departure: "2023-09-09T07:30:00Z",
        arrival: "2023-09-09T08:45:00Z",
      },
      {
        airline: "Lufthansa",
        flightNumber: "LH1937",
        from: "PSA",
        to: "MUC",
        departure: "2023-09-17T15:10:00Z",
        arrival: "2023-09-17T16:35:00Z",
      },
    ],
    stays: [
      {
        name: "Agriturismo Il Poggio",
        type: "guesthouse",
        city: "San Gimignano",
        country: "Italy",
        iso: "IT",
        lat: 43.4677,
        lon: 11.0435,
        checkIn: "2023-09-09T00:00:00Z",
        checkOut: "2023-09-13T00:00:00Z",
        board: "half",
        price: 780,
        currency: "EUR",
        rating: 5,
        stars: null,
      },
      {
        name: "Appartamento Il Campo",
        type: "apartment",
        city: "Siena",
        country: "Italy",
        iso: "IT",
        lat: 43.3186,
        lon: 11.3316,
        checkIn: "2023-09-13T00:00:00Z",
        checkOut: "2023-09-17T00:00:00Z",
        board: "none",
        price: 560,
        currency: "EUR",
        rating: 4,
        stars: null,
      },
    ],
    places: [
      {
        name: "Dom von Florenz",
        category: "landmark",
        city: "Florenz",
        country: "Italy",
        iso: "IT",
        lat: 43.7731,
        lon: 11.256,
        visitedAt: "2023-09-09T11:00:00Z",
        rating: 5,
        curatedId: "world-heritage:174",
      },
      {
        name: "Ponte Vecchio",
        category: "landmark",
        city: "Florenz",
        country: "Italy",
        iso: "IT",
        lat: 43.768,
        lon: 11.2531,
        visitedAt: "2023-09-09T15:00:00Z",
        rating: 4,
      },
      {
        name: "San Gimignano",
        category: "landmark",
        city: "San Gimignano",
        country: "Italy",
        iso: "IT",
        lat: 43.4677,
        lon: 11.0434,
        visitedAt: "2023-09-10T10:00:00Z",
        rating: 5,
        curatedId: "world-heritage:550",
      },
      {
        name: "Piazza del Campo",
        category: "landmark",
        city: "Siena",
        country: "Italy",
        iso: "IT",
        lat: 43.3183,
        lon: 11.3317,
        visitedAt: "2023-09-14T18:00:00Z",
        rating: 5,
        curatedId: "world-heritage:717",
      },
      {
        name: "Pienza",
        category: "viewpoint",
        city: "Pienza",
        country: "Italy",
        iso: "IT",
        lat: 43.0766,
        lon: 11.679,
        visitedAt: "2023-09-15T11:00:00Z",
        rating: 5,
        curatedId: "world-heritage:789",
      },
      {
        name: "Schiefer Turm von Pisa",
        category: "landmark",
        city: "Pisa",
        country: "Italy",
        iso: "IT",
        lat: 43.723,
        lon: 10.3966,
        visitedAt: "2023-09-17T10:00:00Z",
        rating: 4,
        curatedId: "world-heritage:395",
      },
    ],
    tour: {
      name: "Durch die Hügel",
      mode: "road",
      color: "#fb923c",
      stops: [
        { name: "Florenz", lat: 43.7696, lon: 11.2558 },
        { name: "San Gimignano", lat: 43.4677, lon: 11.0434 },
        { name: "Siena", lat: 43.3188, lon: 11.3308 },
        { name: "Pienza", lat: 43.0766, lon: 11.679 },
        { name: "Pisa", lat: 43.7228, lon: 10.4017 },
      ],
    },
    journal: [
      {
        date: "2023-09-10T21:00:00Z",
        title: "Türme im Abendlicht",
        body: "San Gimignano nach den Tagesbussen — plötzlich still.",
        mood: "entspannt",
        weather: "sonnig, 27 °C",
      },
      {
        date: "2023-09-15T21:00:00Z",
        title: "Val d'Orcia",
        body: "Zypressenallee, Pecorino in Pienza, zu viel Wein.",
        mood: "glücklich",
        weather: "sonnig, 29 °C",
      },
    ],
  },
  {
    name: "Mittelmeer-Kreuzfahrt",
    icon: "🚢",
    color: "#fbbf24",
    status: "completed",
    category: "vacation",
    description: "Von Barcelona über Marseille, Genua und Neapel nach Rom.",
    start: "2024-05-10T00:00:00Z",
    end: "2024-05-17T23:59:00Z",
    origin: "Barcelona",
    destination: "Civitavecchia",
    countries: ["ES", "FR", "IT"],
    tags: ["Kreuzfahrt"],
    companions: ["Anna"],
    flights: [
      {
        airline: "Lufthansa",
        flightNumber: "LH1812",
        from: "MUC",
        to: "BCN",
        departure: "2024-05-10T06:45:00Z",
        arrival: "2024-05-10T08:55:00Z",
      },
      {
        airline: "Lufthansa",
        flightNumber: "LH1869",
        from: "FCO",
        to: "MUC",
        departure: "2024-05-17T16:05:00Z",
        arrival: "2024-05-17T17:40:00Z",
      },
    ],
    stays: [
      {
        name: "Hotel Colón",
        type: "hotel",
        city: "Barcelona",
        country: "Spain",
        iso: "ES",
        lat: 41.3845,
        lon: 2.1762,
        checkIn: "2024-05-10T00:00:00Z",
        checkOut: "2024-05-11T00:00:00Z",
        board: "breakfast",
        price: 240,
        currency: "EUR",
        rating: 4,
        stars: 4,
      },
    ],
    places: [
      {
        name: "Sagrada Família",
        category: "landmark",
        city: "Barcelona",
        country: "Spain",
        iso: "ES",
        lat: 41.4036,
        lon: 2.1744,
        visitedAt: "2024-05-10T15:00:00Z",
        rating: 5,
      },
      {
        name: "Vieux-Port",
        category: "landmark",
        city: "Marseille",
        country: "France",
        iso: "FR",
        lat: 43.2951,
        lon: 5.374,
        visitedAt: "2024-05-12T11:00:00Z",
        rating: 4,
      },
      {
        name: "Pompeji",
        category: "museum",
        city: "Pompei",
        country: "Italy",
        iso: "IT",
        lat: 40.7489,
        lon: 14.4848,
        visitedAt: "2024-05-15T10:00:00Z",
        rating: 5,
        curatedId: "world-heritage:829",
      },
      {
        name: "Kolosseum",
        category: "landmark",
        city: "Rom",
        country: "Italy",
        iso: "IT",
        lat: 41.8902,
        lon: 12.4922,
        visitedAt: "2024-05-17T09:00:00Z",
        rating: 5,
        curatedId: "world-wonders-new7:colosseum",
      },
    ],
    cruise: {
      ship: "MSC Grandiosa",
      start: "2024-05-11T16:00:00Z",
      end: "2024-05-17T08:00:00Z",
      cabinType: "balcony",
      price: 1890,
      stops: [
        { locode: "ESBCN" },
        { locode: "FRMRS" },
        { locode: "ITGOA" },
        { atSea: true },
        { locode: "ITNAP" },
        { atSea: true },
        { locode: "ITCVV" },
      ],
    },
    journal: [
      {
        date: "2024-05-15T21:00:00Z",
        title: "Pompeji",
        body: "Landausflug in der Mittagshitze, trotzdem der beste Tag der Reise.",
        mood: "beeindruckt",
        weather: "sonnig, 26 °C",
      },
    ],
  },
  {
    name: "Norwegens Fjorde",
    icon: "🏔️",
    color: "#818cf8",
    status: "completed",
    category: "vacation",
    description: "Mit AIDAsol die Küste hinauf bis über den Polarkreis.",
    start: "2025-07-05T00:00:00Z",
    end: "2025-07-13T23:59:00Z",
    origin: "Bergen",
    destination: "Tromsø",
    countries: ["NO"],
    tags: ["Kreuzfahrt", "Polarkreis"],
    companions: ["Jonas"],
    flights: [
      {
        airline: "Lufthansa",
        flightNumber: "LH2458",
        from: "MUC",
        to: "BGO",
        departure: "2025-07-05T09:10:00Z",
        arrival: "2025-07-05T11:35:00Z",
      },
      {
        airline: "Norwegian",
        flightNumber: "DY391",
        from: "TOS",
        to: "OSL",
        departure: "2025-07-13T10:00:00Z",
        arrival: "2025-07-13T11:50:00Z",
      },
      {
        airline: "Lufthansa",
        flightNumber: "LH2455",
        from: "OSL",
        to: "MUC",
        departure: "2025-07-13T13:30:00Z",
        arrival: "2025-07-13T15:45:00Z",
      },
    ],
    stays: [],
    places: [
      {
        name: "Bryggen",
        category: "landmark",
        city: "Bergen",
        country: "Norway",
        iso: "NO",
        lat: 60.3975,
        lon: 5.3233,
        visitedAt: "2025-07-05T15:00:00Z",
        rating: 4,
        curatedId: "world-heritage:59",
      },
      {
        name: "Aussichtspunkt Aksla",
        category: "viewpoint",
        city: "Ålesund",
        country: "Norway",
        iso: "NO",
        lat: 62.4722,
        lon: 6.16,
        visitedAt: "2025-07-07T10:00:00Z",
        rating: 5,
      },
      {
        name: "Nidarosdom",
        category: "landmark",
        city: "Trondheim",
        country: "Norway",
        iso: "NO",
        lat: 63.4269,
        lon: 10.3969,
        visitedAt: "2025-07-09T11:00:00Z",
        rating: 4,
      },
      {
        name: "Eismeerkathedrale",
        category: "landmark",
        city: "Tromsø",
        country: "Norway",
        iso: "NO",
        lat: 69.6481,
        lon: 18.9876,
        visitedAt: "2025-07-12T16:00:00Z",
        rating: 4,
      },
    ],
    cruise: {
      ship: "AIDAsol",
      start: "2025-07-05T18:00:00Z",
      end: "2025-07-13T07:00:00Z",
      cabinType: "oceanview",
      price: 2150,
      stops: [
        { locode: "NOBGO" },
        { atSea: true },
        { locode: "NOAES" },
        { atSea: true },
        { locode: "NOTRD" },
        { locode: "NOBOO" },
        { atSea: true },
        { locode: "NOTOS" },
      ],
    },
    journal: [
      {
        date: "2025-07-10T23:00:00Z",
        title: "Polarkreis",
        body: "Taufe an Deck um Mitternacht, die Sonne ging einfach nicht unter.",
        mood: "ausgelassen",
        weather: "klar, 13 °C",
      },
    ],
  },
  {
    name: "Portugal",
    icon: "🇵🇹",
    color: "#34d399",
    status: "planned",
    category: "vacation",
    description: "Lissabon, Sintra und die Küste hinauf nach Porto.",
    start: "2027-06-05T00:00:00Z",
    end: "2027-06-12T23:59:00Z",
    origin: "Lissabon",
    destination: "Porto",
    countries: ["PT"],
    tags: ["Roadtrip"],
    companions: ["Anna"],
    flights: [
      {
        airline: "TAP Air Portugal",
        flightNumber: "TP557",
        from: "MUC",
        to: "LIS",
        departure: "2027-06-05T06:25:00Z",
        arrival: "2027-06-05T09:20:00Z",
      },
      {
        airline: "Lufthansa",
        flightNumber: "LH1781",
        from: "OPO",
        to: "MUC",
        departure: "2027-06-12T12:15:00Z",
        arrival: "2027-06-12T15:55:00Z",
      },
    ],
    stays: [
      {
        name: "Memmo Alfama",
        type: "hotel",
        city: "Lissabon",
        country: "Portugal",
        iso: "PT",
        lat: 38.711,
        lon: -9.13,
        checkIn: "2027-06-05T00:00:00Z",
        checkOut: "2027-06-09T00:00:00Z",
        board: "breakfast",
        price: 960,
        currency: "EUR",
        rating: null,
        stars: 4,
      },
      {
        name: "Pestana Vintage Porto",
        type: "hotel",
        city: "Porto",
        country: "Portugal",
        iso: "PT",
        lat: 41.1405,
        lon: -8.6132,
        checkIn: "2027-06-09T00:00:00Z",
        checkOut: "2027-06-12T00:00:00Z",
        board: "breakfast",
        price: 690,
        currency: "EUR",
        rating: null,
        stars: 5,
      },
    ],
    places: [
      {
        name: "Torre de Belém",
        category: "landmark",
        city: "Lissabon",
        country: "Portugal",
        iso: "PT",
        lat: 38.6916,
        lon: -9.216,
        visitedAt: null,
        rating: null,
        curatedId: "world-heritage:263",
      },
      {
        name: "Palácio da Pena",
        category: "landmark",
        city: "Sintra",
        country: "Portugal",
        iso: "PT",
        lat: 38.7876,
        lon: -9.3906,
        visitedAt: null,
        rating: null,
        curatedId: "world-heritage:723",
      },
      {
        name: "Ribeira",
        category: "landmark",
        city: "Porto",
        country: "Portugal",
        iso: "PT",
        lat: 41.1407,
        lon: -8.613,
        visitedAt: null,
        rating: null,
        curatedId: "world-heritage:755",
      },
      {
        name: "Livraria Lello",
        category: "shopping",
        city: "Porto",
        country: "Portugal",
        iso: "PT",
        lat: 41.1469,
        lon: -8.6149,
        visitedAt: null,
        rating: null,
      },
    ],
    tour: {
      name: "Küste nach Norden",
      mode: "road",
      color: "#34d399",
      stops: [
        { name: "Lissabon", lat: 38.7223, lon: -9.1393 },
        { name: "Sintra", lat: 38.8029, lon: -9.3817 },
        { name: "Óbidos", lat: 39.3606, lon: -9.1571 },
        { name: "Coimbra", lat: 40.2033, lon: -8.4103 },
        { name: "Porto", lat: 41.1579, lon: -8.6291 },
      ],
    },
    journal: [],
  },
];
