import fs from "fs";
import path from "path";

import { readPhotoExif } from "../photoExif";

/**
 * forgejo#192: capture time and position come out of the file's own EXIF —
 * including a HEIC container, where an iPhone keeps them.
 *
 * Fixtures are synthetic (a computed gradient, made-up EXIF at the Eiffel
 * Tower) and regenerated by `__tests__/fixtures/photos/make-photo-fixtures.py`.
 */
const FIXTURES = path.join(__dirname, "../../../__tests__/fixtures/photos");
const read = (name: string): Buffer => fs.readFileSync(path.join(FIXTURES, name));

describe("readPhotoExif", () => {
  it("reads capture time, offset and position from a real HEVC-coded HEIC", () => {
    const exif = readPhotoExif(read("synthetic-exif.heic"));

    // 14:23:45 at +02:00 — the offset makes the instant exact.
    expect(exif.takenAt?.toISOString()).toBe("2024-05-17T12:23:45.000Z");
    expect(exif.lat).toBeCloseTo(48.858222, 5);
    expect(exif.lon).toBeCloseTo(2.2945, 5);
  });

  it("places a capture time without an offset in the zone of the photo's own position", () => {
    // Paris in May is CEST (+02:00): 14:23:45 local is 12:23:45Z. Reading it in
    // the server's zone instead would be off by the host's offset.
    const exif = readPhotoExif(read("synthetic-exif-no-offset.jpg"));

    expect(exif.takenAt?.toISOString()).toBe("2024-05-17T12:23:45.000Z");
    expect(exif.lat).toBeCloseTo(48.858222, 5);
  });

  it("abstains — nulls, not the upload time — for bytes with no metadata", () => {
    const png = Buffer.concat([
      Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
      Buffer.alloc(64, 7),
    ]);

    expect(readPhotoExif(png)).toEqual({ takenAt: null, lat: null, lon: null });
    expect(readPhotoExif(Buffer.from("not an image"))).toEqual({
      takenAt: null,
      lat: null,
      lon: null,
    });
  });
});
