/**
 * Downloads the three font families of the design system into
 * `public/fonts/` and writes `src/theme/fonts.css` to match.
 *
 * Why self-hosted at all: the app's CSP has no `fonts.googleapis.com` in
 * `style-src` and no `fonts.gstatic.com` in `font-src`, so the stylesheet link
 * the old `index.html` carried was already a request the browser refuses on any
 * instance that sets the header. A self-hosted face also survives an instance
 * that runs without internet access, which is the normal case for a homelab.
 *
 * Run manually — `node scripts/fetch-fonts.mjs` — when a weight or a family
 * changes in `design/tokens.json`. The downloaded files are checked in, so a
 * normal build and CI never reach the network.
 */
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const fontDir = resolve(here, "../public/fonts");
const cssPath = resolve(here, "../src/theme/fonts.css");

/**
 * Google's css2 endpoint serves woff2 only when it believes the client can
 * read it; a bare fetch gets the truetype fallback, which is three times the
 * size for the same glyphs.
 */
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

/** Only the subsets the UI actually needs. Cyrillic and Vietnamese are dead weight for a DE/EN app. */
const KEEP_SUBSETS = new Set(["latin", "latin-ext"]);

const FAMILIES = [
  { family: "Hanken Grotesk", spec: "wght@400;500;600;700;800", slug: "hanken-grotesk" },
  { family: "IBM Plex Mono", spec: "wght@400;500;600", slug: "ibm-plex-mono" },
  { family: "Newsreader", spec: "ital,wght@1,400;1,500", slug: "newsreader" },
];

/** Parses the `/* subset *\/` comments Google emits above each @font-face. */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    const [, subset, body] = m;
    const pick = (key) => (body.match(new RegExp(`${key}:\\s*([^;]+);`)) ?? [])[1]?.trim();
    const url = (body.match(/url\(([^)]+)\)/) ?? [])[1];
    faces.push({
      subset,
      style: pick("font-style") ?? "normal",
      weight: pick("font-weight") ?? "400",
      unicodeRange: pick("unicode-range"),
      url,
    });
  }
  return faces;
}

mkdirSync(fontDir, { recursive: true });

const blocks = [];
for (const { family, spec, slug } of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%20/g, "+")}:${spec}&display=swap`;
  const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.text());
  for (const face of parseFaces(css)) {
    if (!KEEP_SUBSETS.has(face.subset)) continue;
    const italic = face.style === "italic" ? "-italic" : "";
    const name = `${slug}-${face.weight}${italic}-${face.subset}.woff2`;
    const target = resolve(fontDir, name);
    if (!existsSync(target)) {
      const bytes = await fetch(face.url, { headers: { "User-Agent": UA } }).then((r) =>
        r.arrayBuffer()
      );
      writeFileSync(target, Buffer.from(bytes));
      console.log(`downloaded ${name} (${Math.round(bytes.byteLength / 1024)} kB)`);
    }
    blocks.push(
      [
        "@font-face {",
        `  font-family: "${family}";`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        "  font-display: swap;",
        `  src: url("/fonts/${name}") format("woff2");`,
        `  unicode-range: ${face.unicodeRange};`,
        "}",
      ].join("\n")
    );
  }
}

const header = `/*
 * GENERATED by scripts/fetch-fonts.mjs — do not edit by hand.
 *
 * Self-hosted so no instance depends on fonts.gstatic.com being reachable and
 * no stylesheet has to be allowed past the CSP. Latin and Latin-Extended only;
 * the DE/EN interface needs nothing else.
 */

`;

mkdirSync(dirname(cssPath), { recursive: true });
writeFileSync(cssPath, header + blocks.join("\n\n") + "\n", "utf8");
console.log(`wrote ${cssPath} (${blocks.length} faces)`);
