/**
 * Evidence measures — flight tab, part 1: headline metrics, business
 * statistics, airport statistics, punctuality. See `evidenceMeasures.ts`
 * for what this file is part of and why it is split out.
 *
 * MIRRORED at `frontend/src/shared/evidenceMeasuresFlightCore.ts`.
 */
import type { MeasureSpec } from "./evidenceMeasures";

export const FLIGHT_CORE_MEASURES: Record<string, MeasureSpec> = {
  // ── Headline metrics (StatsOverviewCards, StatsDistanceSection, StatsFlightBreakdown) ──
  flightCount: {
    aggregation: "sum",
    unit: "flights",
    scope: "allTime",
    surface: "StatsOverviewCards",
    calculator: "AdvancedStatsPage.tsx (client reduce over flightsApi.getAll, isCountableFlight)",
    servedIn: 1,
  },
  flightTimeMinutes: {
    aggregation: "sum",
    unit: "minutes",
    scope: "allTime",
    surface: "StatsOverviewCards",
    calculator: "shared/flightDuration.ts addFlightDuration (client fold)",
    servedIn: 1,
  },
  avgFlightDurationMinutes: {
    aggregation: "ratio",
    unit: "minutes",
    scope: "allTime",
    surface: "StatsOverviewCards",
    calculator: "shared/flightDuration.ts averageDurationMinutes",
    servedIn: 2,
  },
  airlineCount: {
    aggregation: "distinct",
    unit: "airlines",
    scope: "allTime",
    surface: "StatsOverviewCards",
    calculator: "shared/airlineNormalize.ts groupAirlines (client fold)",
    servedIn: 1,
  },
  distanceKmTotal: {
    aggregation: "sum",
    unit: "km",
    scope: "allTime",
    surface: "StatsDistanceSection",
    calculator: "AdvancedStatsPage.tsx (client Haversine reduce)",
    servedIn: 1,
  },
  avgDistanceKm: {
    aggregation: "ratio",
    unit: "km",
    scope: "allTime",
    surface: "StatsDistanceSection",
    calculator: "AdvancedStatsPage.tsx (client Haversine reduce)",
    servedIn: 2,
  },
  distanceMilestoneShare: {
    aggregation: "ratio",
    unit: "%",
    scope: "allTime",
    surface: "StatsDistanceSection",
    calculator: "AdvancedStatsPage.tsx totalDistance / a fixed constant (earth/moon/mars/voyager)",
    servedIn: 2,
  },
  longestFlightDistanceKm: {
    aggregation: "extremum",
    unit: "km",
    scope: "allTime",
    surface: "StatsDistanceSection",
    calculator: "AdvancedStatsPage.tsx flightDistances.sort()",
    servedIn: 2,
  },
  shortestFlightDistanceKm: {
    aggregation: "extremum",
    unit: "km",
    scope: "allTime",
    surface: "StatsDistanceSection",
    calculator: "AdvancedStatsPage.tsx flightDistances.sort()",
    servedIn: 2,
  },
  longestFlightDurationMinutes: {
    aggregation: "extremum",
    unit: "minutes",
    scope: "allTime",
    surface: "StatsFlightBreakdown",
    calculator: "AdvancedStatsPage.tsx flightDurations.sort()",
    servedIn: 2,
  },
  shortestFlightDurationMinutes: {
    aggregation: "extremum",
    unit: "minutes",
    scope: "allTime",
    surface: "StatsFlightBreakdown",
    calculator: "AdvancedStatsPage.tsx flightDurations.sort()",
    servedIn: 2,
  },
  flightsWithoutAirlineCount: {
    aggregation: "sum",
    unit: "flights",
    scope: "allTime",
    surface: "StatsFlightBreakdown",
    calculator: "GET /stats/airlines (shared/airlineNormalize.ts groupAirlines, withoutAirline)",
    servedIn: 1,
  },
  scorecardFlightCount: {
    aggregation: "sum",
    unit: "flights",
    scope: "rolling12m",
    surface: "scorecard/FlightScorecardBlock",
    calculator: "GET /stats/timeseries (services/stats/timeseriesRows.ts)",
    servedIn: 1,
  },
  scorecardDistanceKm: {
    aggregation: "sum",
    unit: "km",
    scope: "rolling12m",
    surface: "scorecard/FlightScorecardBlock",
    calculator: "GET /stats/timeseries (services/stats/timeseriesRows.ts)",
    servedIn: 1,
  },
  scorecardFlightTimeMinutes: {
    aggregation: "sum",
    unit: "minutes",
    scope: "rolling12m",
    surface: "scorecard/FlightScorecardBlock",
    calculator: "GET /stats/timeseries (services/stats/timeseriesRows.ts)",
    servedIn: 1,
  },
  yearFlightCount: {
    aggregation: "sum",
    unit: "flights",
    scope: "year",
    surface: "FlightYearSummaryCards",
    calculator: "GET /stats/summary?year= (services/stats/summary.ts computeSummary)",
    servedIn: 1,
  },
  yearDistanceKm: {
    aggregation: "sum",
    unit: "km",
    scope: "year",
    surface: "FlightYearSummaryCards",
    calculator: "GET /stats/summary?year= (services/stats/summary.ts computeSummary)",
    servedIn: 1,
  },
  yearFlightTimeMinutes: {
    aggregation: "sum",
    unit: "minutes",
    scope: "year",
    surface: "FlightYearSummaryCards",
    calculator: "GET /stats/summary?year= (services/stats/summary.ts computeSummary)",
    servedIn: 1,
  },
  yearTotalCost: {
    aggregation: "sum",
    unit: "currency",
    scope: "year",
    surface: "FlightYearSummaryCards",
    calculator: "GET /stats/summary?year= (services/stats/summary.ts computeSummary)",
    servedIn: 1,
  },
  yearUnpricedFlightCount: {
    aggregation: "sum",
    unit: "flights",
    scope: "year",
    surface: "FlightYearSummaryCards",
    calculator: "GET /stats/summary?year= (services/stats/summary.ts computeSummary)",
    servedIn: 1,
  },

  // ── Business statistics (StatsBusinessSection) ──
  businessTotalCost: {
    aggregation: "sum",
    unit: "currency",
    scope: "allTime",
    surface: "StatsBusinessSection",
    calculator: "GET /stats/business (utils/stats/businessStats.ts calculateBusinessStats)",
    servedIn: 1,
  },
  businessCostPerKm: {
    aggregation: "ratio",
    unit: "currency/km",
    scope: "allTime",
    surface: "StatsBusinessSection",
    calculator: "GET /stats/business (utils/stats/businessStats.ts calculateBusinessStats)",
    servedIn: 2,
  },
  businessCostPerHour: {
    aggregation: "ratio",
    unit: "currency/hour",
    scope: "allTime",
    surface: "StatsBusinessSection",
    calculator: "GET /stats/business (utils/stats/businessStats.ts calculateBusinessStats)",
    servedIn: 2,
  },
  airportsVisitedCount: {
    aggregation: "distinct",
    unit: "airports",
    scope: "allTime",
    surface: "StatsBusinessSection, StatsAirportsSection",
    calculator:
      "GET /stats/business (calculateBusinessStats.airportDiversity) or GET /stats/airports (calculateAirportStats.airportCount) — same question, two calculators, kept as one key",
    servedIn: 1,
  },
  businessAvgFlightDurationMinutes: {
    aggregation: "ratio",
    unit: "minutes",
    scope: "allTime",
    surface: "StatsBusinessSection",
    calculator: "GET /stats/business (utils/stats/businessStats.ts calculateBusinessStats)",
    servedIn: 2,
  },
  busiestMonthFlightCount: {
    aggregation: "extremum",
    unit: "flights",
    scope: "allTime",
    surface: "StatsBusinessSection",
    calculator: "GET /stats/business (utils/stats/businessStats.ts calculateBusinessStats)",
    servedIn: 2,
  },
  mostCommonBookingCategory: {
    aggregation: "extremum",
    unit: "category",
    scope: "allTime",
    surface: "StatsBusinessSection",
    calculator: "GET /stats/business (utils/stats/businessStats.ts calculateBusinessStats)",
    servedIn: 2,
  },

  // ── Airport statistics (StatsAirportsSection) ──
  flightCountriesVisitedCount: {
    aggregation: "distinct",
    unit: "countries",
    scope: "allTime",
    surface: "StatsAirportsSection",
    calculator: "GET /stats/airports (utils/stats/airportStats.ts calculateAirportStats)",
    servedIn: 1,
  },
  continentsVisitedCount: {
    aggregation: "distinct",
    unit: "continents",
    scope: "allTime",
    surface: "StatsAirportsSection",
    calculator: "GET /stats/airports (utils/stats/airportStats.ts calculateAirportStats)",
    servedIn: 1,
  },
  farthestAirportDistanceKm: {
    aggregation: "extremum",
    unit: "km",
    scope: "allTime",
    surface: "StatsAirportsSection",
    calculator: "GET /stats/airports (utils/stats/airportStats.ts calculateAirportStats)",
    servedIn: 2,
  },

  // ── Punctuality (PunctualitySection) ──
  punctualitySampleSize: {
    aggregation: "sum",
    unit: "flights",
    scope: "allTime",
    surface: "PunctualitySection",
    calculator: "GET /stats/punctuality (services/punctualityStats.ts)",
    servedIn: 1,
  },
  punctualityAvgDelayMinutes: {
    aggregation: "ratio",
    unit: "minutes",
    scope: "allTime",
    surface: "PunctualitySection",
    calculator: "GET /stats/punctuality (services/punctualityStats.ts)",
    servedIn: 2,
  },
  punctualityOnTimeRate: {
    aggregation: "ratio",
    unit: "%",
    scope: "allTime",
    surface: "PunctualitySection",
    calculator: "GET /stats/punctuality (services/punctualityStats.ts)",
    servedIn: 2,
  },
  punctualityBestAirlineDelay: {
    aggregation: "extremum",
    unit: "minutes",
    scope: "allTime",
    surface: "PunctualitySection",
    calculator: "GET /stats/punctuality (services/punctualityStats.ts)",
    servedIn: 2,
  },
  punctualityWorstAirlineDelay: {
    aggregation: "extremum",
    unit: "minutes",
    scope: "allTime",
    surface: "PunctualitySection",
    calculator: "GET /stats/punctuality (services/punctualityStats.ts)",
    servedIn: 2,
  },
  punctualityWorstRouteDelay: {
    aggregation: "extremum",
    unit: "minutes",
    scope: "allTime",
    surface: "PunctualitySection",
    calculator: "GET /stats/punctuality (services/punctualityStats.ts)",
    servedIn: 2,
  },
};
