/**
 * Evidence measures — cruise, lodging and places tabs. See
 * `evidenceMeasures.ts` for what this file is part of and why it is split
 * out.
 *
 * MIRRORED at `frontend/src/shared/evidenceMeasuresDomains.ts`.
 */
import type { MeasureSpec } from "./evidenceMeasures";

const CRUISE_CALCULATOR = "GET /stats/cruise?year= (utils/cruiseStats.ts calculateCruiseStats)";
const CRUISE_DETAIL_CALCULATOR = "lib/stats/cruiseStatsDetail.ts deriveCruiseStats (client fold)";
const LODGING_CALCULATOR =
  "GET /lodging/stats?year= (utils/lodgingStats/index.ts calculateLodgingStats)";
const POI_CALCULATOR = "lib/stats/poiStatsDetail.ts derivePoiStats (client fold over listPlaces)";

export const DOMAIN_MEASURES: Record<string, MeasureSpec> = {
  // ── Cruise tab (CruiseStatsSection) ──
  cruiseCount: {
    aggregation: "sum",
    unit: "cruises",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 1,
  },
  cruiseDistanceKmTotal: {
    aggregation: "sum",
    unit: "km",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 1,
  },
  cruiseSeaDaysTotal: {
    aggregation: "sum",
    unit: "days",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 1,
  },
  cruisePortsUniqueCount: {
    aggregation: "distinct",
    unit: "ports",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 1,
  },
  cruiseShipsUniqueCount: {
    aggregation: "distinct",
    unit: "ships",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 1,
  },
  cruiseLinesUniqueCount: {
    aggregation: "distinct",
    unit: "lines",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 1,
  },
  cruiseTotalDays: {
    aggregation: "sum",
    unit: "days",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 1,
  },
  cruiseCountriesCount: {
    aggregation: "distinct",
    unit: "countries",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 1,
  },
  cruiseAvgPortsPerCruise: {
    aggregation: "ratio",
    unit: "ports/cruise",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 2,
  },
  cruiseLongestLegKm: {
    aggregation: "extremum",
    unit: "km",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 2,
  },
  cruisePortsSingleTripMax: {
    aggregation: "extremum",
    unit: "ports",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 2,
  },
  cruiseLineLoyaltyMax: {
    aggregation: "extremum",
    unit: "cruises",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 2,
  },
  cruiseSeaDaysStreak: {
    aggregation: "sequence",
    unit: "days",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 2,
  },
  cruiseMaxDeck: {
    aggregation: "extremum",
    unit: "deck",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 2,
  },
  cruisePortRevisitRate: {
    aggregation: "ratio",
    unit: "%",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 2,
  },
  cruiseFlagAchieved: {
    aggregation: "boolean",
    unit: "boolean",
    scope: "year",
    surface: "CruiseStatsSection",
    calculator: CRUISE_CALCULATOR,
    servedIn: 2,
  },
  cruiseCompanionCount: {
    aggregation: "sum",
    unit: "companions",
    scope: "year",
    surface: "CruiseStatsSection (CruiseFunSection)",
    calculator: CRUISE_DETAIL_CALCULATOR,
    servedIn: 1,
  },
  cruiseTotalSpend: {
    aggregation: "sum",
    unit: "currency",
    scope: "year",
    surface: "CruiseStatsSection (CruiseMoneySection)",
    calculator: CRUISE_DETAIL_CALCULATOR,
    servedIn: 1,
  },

  // ── Lodging tab (LodgingStatsSection) ──
  lodgingStaysCount: {
    aggregation: "sum",
    unit: "stays",
    scope: "year",
    surface: "LodgingStatsSection",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingNightsTotal: {
    aggregation: "sum",
    unit: "nights",
    scope: "year",
    surface: "LodgingStatsSection",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingsUniqueCount: {
    aggregation: "distinct",
    unit: "lodgings",
    scope: "year",
    surface: "LodgingStatsSection",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingCountriesCount: {
    aggregation: "distinct",
    unit: "countries",
    scope: "year",
    surface: "LodgingStatsSection",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingSpendTotal: {
    aggregation: "sum",
    unit: "currency",
    scope: "year",
    surface: "LodgingStatsSection (LodgingCurrencyBreakdown)",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingAvgCostPerNight: {
    aggregation: "ratio",
    unit: "currency/night",
    scope: "year",
    surface: "LodgingStatsSection (LodgingMoneySection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 2,
  },
  lodgingAwardNightsCount: {
    aggregation: "sum",
    unit: "nights",
    scope: "year",
    surface: "LodgingStatsSection (LodgingMoneySection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingAvgOverallRating: {
    aggregation: "ratio",
    unit: "stars",
    scope: "year",
    surface: "LodgingStatsSection (LodgingQualitySection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 2,
  },
  lodgingContinentsCount: {
    aggregation: "distinct",
    unit: "continents",
    scope: "year",
    surface: "LodgingStatsSection (LodgingGeoSection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingNightsAwayTotal: {
    aggregation: "sum",
    unit: "nights",
    scope: "year",
    surface: "LodgingStatsSection (LodgingRhythmSection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingTopChainShare: {
    aggregation: "ratio",
    unit: "%",
    scope: "year",
    surface: "LodgingStatsSection (LodgingLoyaltySection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 2,
  },
  lodgingLongestStayNights: {
    aggregation: "extremum",
    unit: "nights",
    scope: "year",
    surface: "LodgingStatsSection (LodgingRecordsSection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 2,
  },
  lodgingOneNightStayCount: {
    aggregation: "sum",
    unit: "stays",
    scope: "year",
    surface: "LodgingStatsSection (LodgingRecordsSection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },
  lodgingPerfectStayCount: {
    aggregation: "sum",
    unit: "stays",
    scope: "year",
    surface: "LodgingStatsSection (LodgingRecordsSection)",
    calculator: LODGING_CALCULATOR,
    servedIn: 1,
  },

  // ── Places tab (PoiStatsSection) ──
  placesVisitedCount: {
    aggregation: "distinct",
    unit: "places",
    scope: "year",
    surface: "PoiStatsSection",
    calculator: POI_CALCULATOR,
    servedIn: 1,
  },
  placeVisitCount: {
    aggregation: "sum",
    unit: "visits",
    scope: "year",
    surface: "PoiStatsSection",
    calculator: POI_CALCULATOR,
    servedIn: 1,
  },
  placeCountriesCount: {
    aggregation: "distinct",
    unit: "countries",
    scope: "year",
    surface: "PoiStatsSection",
    calculator: POI_CALCULATOR,
    servedIn: 1,
  },
  placeCitiesCount: {
    aggregation: "distinct",
    unit: "cities",
    scope: "year",
    surface: "PoiStatsSection",
    calculator: POI_CALCULATOR,
    servedIn: 1,
  },
  placeListCount: {
    aggregation: "sum",
    unit: "lists",
    scope: "allTime",
    surface: "PoiStatsSection",
    calculator: "listPlaceLists/listCuratedChecklists (client fold, no year scope)",
    servedIn: 1,
  },
  placeWishlistCount: {
    aggregation: "sum",
    unit: "places",
    scope: "allTime",
    surface: "PoiStatsSection",
    calculator: POI_CALCULATOR,
    servedIn: 1,
  },
  placeVisitStreakLength: {
    aggregation: "sequence",
    unit: "days",
    scope: "year",
    surface: "PoiStatsSection (PoiRhythmSection)",
    calculator: POI_CALCULATOR,
    servedIn: 2,
  },
  placeCategoryCoveragePct: {
    aggregation: "ratio",
    unit: "%",
    scope: "year",
    surface: "PoiStatsSection (PoiFunSection)",
    calculator: POI_CALCULATOR,
    servedIn: 2,
  },
  placeAvgRating: {
    aggregation: "ratio",
    unit: "stars",
    scope: "year",
    surface: "PoiStatsSection (PoiQualitySection)",
    calculator: POI_CALCULATOR,
    servedIn: 2,
  },
};
