import type { Flight, Prisma } from "../../../prisma";
import { jsonForWrite, pickFacts } from "./pick";

/**
 * A flight's facts (design 2026-10-09, decision 2): what is true for everyone
 * on board. Private and therefore absent: seat, class, boarding group, booking
 * reference, ticket, price and FX snapshot, category, tags, companions, notes,
 * receipt, frequent-flyer number, baggage, parser provenance.
 *
 * The route measurements (`actualRoute`, `routeDistance`, overflown countries,
 * CO₂) describe the aircraft's path, which is one path for every passenger —
 * copying them is what lets both accounts' distance statistics count the
 * flight without a second lookup. `durationMinutes` is generated by Postgres
 * and never written.
 */
export const FLIGHT_FACT_FIELDS = [
  "airline",
  "airlineIata",
  "airlineIcao",
  "operatingAirline",
  "operatingAirlineIata",
  "operatingAirlineIcao",
  "isCodeshare",
  "flightNumber",
  "callsign",
  "aircraft",
  "aircraftRegistration",
  "aircraftModeS",
  "depIcao",
  "depIata",
  "depName",
  "depLat",
  "depLon",
  "arrIcao",
  "arrIata",
  "arrName",
  "arrLat",
  "arrLon",
  "departureTime",
  "arrivalTime",
  "depTimeSemantics",
  "arrTimeSemantics",
  "depTimezone",
  "arrTimezone",
  "depPrecision",
  "arrPrecision",
  "status",
  "gate",
  "terminal",
  "actualDeparture",
  "actualArrival",
  "delayMinutes",
  "runwayDepartureTime",
  "runwayArrivalTime",
  "actualRoute",
  "overflownCountries",
  "routeDistance",
  "routeSource",
  "co2Kg",
  "specialType",
  "eventLat",
  "eventLon",
  "eventLabel",
  "patternLat",
  "patternLon",
  "specialData",
] as const satisfies readonly (keyof Flight)[];

export type FlightFactField = (typeof FLIGHT_FACT_FIELDS)[number];

/** The facts of `row`, shaped for a Prisma write. */
export function flightFacts(row: Pick<Flight, FlightFactField>) {
  const facts = pickFacts(row, FLIGHT_FACT_FIELDS);
  return {
    ...facts,
    actualRoute: jsonForWrite(facts.actualRoute),
    specialData: jsonForWrite(facts.specialData),
  } satisfies Partial<Prisma.FlightUncheckedCreateInput>;
}
