-- Repair airport names that carry OurAirports' duplicate marker.
--
-- The upstream CSV writes editorial markers INTO the name column
-- ("[Duplicate] Beijing Xijiao Airport", "Sayma (duplicate)"); the seeder
-- passed them through verbatim, so they reached the airport picker as part of
-- the airport's name. The seeder now strips them, but that alone does NOT
-- clean the catalogue: a marked row whose CSV counterpart has since been
-- renamed or retyped upstream is an orphan no re-seed ever matches again --
-- and those orphans are exactly the rows carrying real IATA codes (VLO Vlora,
-- WFR Wolf's Fang). Repairing them here is the only way they ever get fixed.
--
-- The rows are NOT deleted: for those codes the marked row is the only one in
-- the catalogue, so dropping it would remove the code entirely.
--
-- The statement below is generated by `buildDuplicateMarkerCleanupSql` in
-- backend/src/shared/airportName.ts and pinned to it by a test, so the rule
-- here and the rule the importer applies cannot drift apart.

UPDATE "airports"
SET "name" = btrim(regexp_replace(regexp_replace("name", '[([{][^)\]}]*duplicate[^)\]}]*[)\]}]', ' ', 'gi'), '\s+', ' ', 'g'))
WHERE "name" ~* '[([{][^)\]}]*duplicate[^)\]}]*[)\]}]'
  AND btrim(regexp_replace(regexp_replace("name", '[([{][^)\]}]*duplicate[^)\]}]*[)\]}]', ' ', 'gi'), '\s+', ' ', 'g')) <> '';
